import Head from "next/head";
import Header from "../components/header/Index.js";
import InfoSection from "../components/infoSection/InfoSection.js";
import StatisticSection from "../components/statisticSection/StatisticSection.js";
import BoostSection from "../components/boostSection/BoostSection.js";
import FooterSection from "../components/footerSection/FooterSection.js";

export default function Home() {
  return (
    <>
      <Head>
        <title>Shortening</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Header />
        <InfoSection />
        <StatisticSection />
        <BoostSection />
        <FooterSection />
      </main>
    </>
  );
}
